using System.Collections.Generic;
using System.Reflection;

namespace Console.Internal
{
    /// <summary>
    /// The default config
    /// </summary>
    public static class Config
    {
		// CONFIG
		public static int maxHistoryLength { get; private set; } = 300;
		public static int maxInputHistoryLength { get; private set; } = 1000;
		/// <summary>
		/// If a period is followed by a character in this list, the period will be treated as part of the string rather than as a seperator.
		/// This is specifically used to allow the user to enter a number (ex 0.5) without the the period splitting the string
		/// </summary>
		private static HashSet<char> scopingNullifiers = new HashSet<char>( new char[]
		{
			'0',
			'1',
			'2',
			'3',
			'4',
			'5',
			'6',
			'7',
			'8',
			'9',
		});
		/// <summary>
		/// Assemblies in this list will NOT be scanned for console commands
		/// </summary>
		static HashSet<string> assemblyBlacklist = new HashSet<string>(new string[]
		{
			//"IzzysConsoleExample", // Uncommenting this line will remove the example project commands
			"mscorlib",
			"UnityEngine",
			"UnityEngine.AIModule",
			"UnityEngine.ARModule",
			"UnityEngine.AccessibilityModule",
			"UnityEngine.AndroidJNIModule",
			"UnityEngine.AnimationModule",
			"UnityEngine.AssetBundleModule",
			"UnityEngine.AudioModule",
			"UnityEngine.ClothModule",
			"UnityEngine.ClusterInputModule",
			"UnityEngine.ClusterRendererModule",
			"UnityEngine.CoreModule",
			"UnityEngine.CrashReportingModule",
			"UnityEngine.DSPGraphModule",
			"UnityEngine.DirectorModule",
			"UnityEngine.GIModule",
			"UnityEngine.GameCenterModule",
			"UnityEngine.GridModule",
			"UnityEngine.HotReloadModule",
			"UnityEngine.IMGUIModule",
			"UnityEngine.ImageConversionModule",
			"UnityEngine.InputModule",
			"UnityEngine.InputLegacyModule",
			"UnityEngine.JSONSerializeModule",
			"UnityEngine.LocalizationModule",
			"UnityEngine.NVIDIAModule",
			"UnityEngine.ParticleSystemModule",
			"UnityEngine.PerformanceReportingModule",
			"UnityEngine.PhysicsModule",
			"UnityEngine.Physics2DModule",
			"UnityEngine.ProfilerModule",
			"UnityEngine.RuntimeInitializeOnLoadManagerInitializerModule",
			"UnityEngine.ScreenCaptureModule",
			"UnityEngine.SharedInternalsModule",
			"UnityEngine.SpriteMaskModule",
			"UnityEngine.SpriteShapeModule",
			"UnityEngine.StreamingModule",
			"UnityEngine.SubstanceModule",
			"UnityEngine.SubsystemsModule",
			"UnityEngine.TLSModule",
			"UnityEngine.TerrainModule",
			"UnityEngine.TerrainPhysicsModule",
			"UnityEngine.TextCoreFontEngineModule",
			"UnityEngine.TextCoreTextEngineModule",
			"UnityEngine.TextRenderingModule",
			"UnityEngine.TilemapModule",
			"UnityEngine.UIModule",
			"UnityEngine.UIElementsModule",
			"UnityEngine.UIElementsNativeModule",
			"UnityEngine.UNETModule",
			"UnityEngine.UmbraModule",
			"UnityEngine.UnityAnalyticsModule",
			"UnityEngine.UnityConnectModule",
			"UnityEngine.UnityCurlModule",
			"UnityEngine.UnityTestProtocolModule",
			"UnityEngine.UnityWebRequestModule",
			"UnityEngine.UnityWebRequestAssetBundleModule",
			"UnityEngine.UnityWebRequestAudioModule",
			"UnityEngine.UnityWebRequestTextureModule",
			"UnityEngine.UnityWebRequestWWWModule",
			"UnityEngine.VFXModule",
			"UnityEngine.VRModule",
			"UnityEngine.VehiclesModule",
			"UnityEngine.VideoModule",
			"UnityEngine.VirtualTexturingModule",
			"UnityEngine.WindModule",
			"UnityEngine.XRModule",
			"UnityEditor",
			"UnityEditor.CoreModule",
			"UnityEditor.DeviceSimulatorModule",
			"UnityEditor.DiagnosticsModule",
			"UnityEditor.GraphViewModule",
			"UnityEditor.PackageManagerUIModule",
			"UnityEditor.QuickSearchModule",
			"UnityEditor.SceneTemplateModule",
			"UnityEditor.TextCoreFontEngineModule",
			"UnityEditor.TextCoreTextEngineModule",
			"UnityEditor.UIBuilderModule",
			"UnityEditor.UIElementsModule",
			"UnityEditor.UIElementsSamplesModule",
			"UnityEditor.UIServiceModule",
			"UnityEditor.UnityConnectModule",
			"System.Core",
			"System",
			"Mono.Security",
			"System.Configuration",
			"System.Xml",
			"System.Numerics",
			"Bee.BeeDriver",
			"netstandard",
			"System.Data",
			"System.Transactions",
			"System.EnterpriseServices",
			"System.Runtime.Serialization",
			"System.ServiceModel.Internals",
			"System.Xml.Linq",
			"UnityEditor.Graphs",
			"UnityEditor.WindowsStandalone.Extensions",
			"Unity.VisualScripting.Flow.Editor",
			"Unity.2D.Tilemap.Extras",
			"Unity.2D.Animation.Editor",
			"Unity.InternalAPIEngineBridge.001",
			"Unity.VSCode.Editor",
			"Unity.2D.PixelPerfect",
			"Unity.2D.Tilemap.Editor",
			"PsdPlugin",
			"Unity.TextMeshPro.Editor",
			"Unity.Services.Core.Telemetry",
			"Unity.VisualStudio.Editor",
			"UnityEngine.TestRunner",
			"Unity.Timeline",
			"Unity.VisualScripting.Core.Editor",
			"Unity.TextMeshPro",
			"Unity.VisualScripting.State.Editor",
			"Unity.Burst.Editor",
			"Unity.Services.Core.Networking",
			"Unity.2D.IK.Editor",
			"Unity.2D.Sprite.Editor",
			"Unity.Burst.CodeGen",
			"Unity.2D.Path.Editor",
			"Unity.VisualScripting.SettingsProvider.Editor",
			"UnityEditor.TestRunner",
			"Unity.VisualScripting.Flow",
			"UnityEditor.UI",
			"Unity.PlasticSCM.Editor",
			"Unity.Rider.Editor",
			"Unity.2D.Psdimporter.Editor",
			"Unity.Services.Core.Internal",
			"UnityEngine.UI",
			"Unity.2D.Tilemap.Extras.Editor",
			"Unity.InternalAPIEditorBridge.001",
			"Unity.Services.Core.Configuration",
			"Unity.Services.Core",
			"Unity.VisualScripting.Core",
			"Unity.Mathematics",
			"Unity.2D.IK.Runtime",
			"Unity.Services.Core.Editor",
			"Unity.Services.Core.Configuration.Editor",
			"Unity.Services.Core.Analytics",
			"Unity.Burst",
			"Unity.Services.Core.Registration",
			"Unity.VisualScripting.Shared.Editor",
			"Unity.Services.Core.Environments",
			"Unity.2D.Animation.Runtime",
			"Unity.2D.PixelPerfect.Editor",
			"Unity.Services.Core.Scheduler",
			"Unity.Services.Core.Environments.Internal",
			"Unity.Timeline.Editor",
			"Unity.CollabProxy.Editor",
			"Unity.Mathematics.Editor",
			"Unity.Services.Core.Threading",
			"Unity.2D.Common.Runtime",
			"Unity.2D.SpriteShape.Editor",
			"Unity.2D.Common.Editor",
			"Unity.2D.SpriteShape.Runtime",
			"Unity.VisualScripting.State",
			"UnityGameConsole.TextMeshProSupport",
			"Unity.Services.Core.Device",
			"Unity.Plastic.Newtonsoft.Json",
			"Unity.Plastic.Antlr3.Runtime",
			"Unity.VisualScripting.YamlDotNet",
			"Unity.Burst.Unsafe",
			"Unity.Burst.Cecil.Mdb",
			"Unity.VisualScripting.TextureAssets",
			"Unity.VisualScripting.IonicZip",
			"Unity.Burst.Cecil.Pdb",
			"Unity.Burst.Cecil",
			"log4net",
			"Unity.Burst.Cecil.Rocks",
			"Unity.VisualScripting.Antlr3.Runtime",
			"Newtonsoft.Json",
			"nunit.framework",
			"unityplastic",
			"Mono.Posix",
			"System.Net.Http",
			"System.Drawing",
			"System.Runtime",
			"PlayerBuildProgramLibrary.Data",
			"Unity.CompilationPipeline.Common",
			"ExCSS.Unity",
			"Unity.Cecil",
			"ScriptCompilationBuildProgram.Data",
			"BeeBuildProgramCommon.Data",
			"Microsoft.CSharp"
		});

        /// <summary>
        /// Returns whether the specified assembly is on the blacklist
        /// </summary>
        public static bool IsAssemblyExcluded(Assembly assembly) => assemblyBlacklist.Contains(assembly.GetName().Name);
        public static bool IsScopingNullifier(char character) => scopingNullifiers.Contains(character);
		// Leave the collection to the garbage collector - we don't need it after it's used
		public static void CleanupAssemblyBlacklist ()
        {
            assemblyBlacklist.Clear();
			assemblyBlacklist = null;
        }
    }
}